version: '3.8'
services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8081:8080"
        - "9091:9090"
  db:
    image: postgres:alpine
    container_name: my_currency_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:

